### ISSUE TITLE
More elegant way to calculate multimodal Gaussians

### ISSUE THREAD

**Issue by mgbaltussen** [Will-Robin/ChromProcess#19]
Hey y'all/@thijsdejong10 

See below code for a more elegant way of creating/calculating multimodal Gaussians. 
It's a single line of numpy/scipy code :)

Leaving this here for future reference

```python
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# newaxis required for correct broadcasting
x = np.linspace(-5,5, 100)[:,np.newaxis]

loc = np.array([-2, 0, 3])
scale = np.array([0.3, 0.5, 1])

amplitude = np.array([0.5, 3.0, 2.0])
baseline = np.array([0.1, 0.2, 0.0])

# Below function creates a summed, weighted multi-modal gaussian. 
# Make sure loc, scale, amplitude, baseline are all the same dim!
pdf = np.sum(amplitude * norm.pdf(x, loc=loc, scale=scale) + baseline, axis=1)

plt.plot(x, pdf)
plt.ylim(0)
plt.show()
```

**Comment by Will-Robin** [comment]
Indeed, quite elegant! Nice suggestion.

When I made the deconvolution module a while ago, I wrote individual functions for each number of Gaussians with an accompanying hard coded call to `scipy.curve_fit` as I couldn't figure out how to make it work with an arbitrary number of parameters. But your suggestion got me thinking, and I realised that there is a way around it by creating a [wrapper](https://github.com/Will-Robin/ChromProcess/blob/new-decon/ChromProcess/Utils/signal_processing/deconvolution.py#L157) for the function to be optimised.

I've made a candidate re-write of the deconvolution module around this suggestion [here](https://github.com/Will-Robin/ChromProcess/blob/new-decon/ChromProcess/Utils/signal_processing/deconvolution.py).

There is a notebook showing how it works in practice [here](https://github.com/Will-Robin/ChromProcess/blob/new-decon/Tutorials/ChromProcess_Introduction_3_deconvolution.ipynb).

@thijsdejong10, what do you think?

**Comment by thijsdejong10** [comment]
I want for an almost identical approach, just using split instead of reshape: 
```
def gaussians(x, *params):
    number_of_gaussians = len(params)//3
    amplitude, centre, sigma = np.array_split(params[:-1],number_of_gaussians)
    baseline = params[-1]
    return np.sum(amplitude * norm.pdf(x, loc=centre, scale=sigma) + baseline, axis=1)
```
I think you approach is nicer because you can skip the len(params)//3 step. Only real difference is that we should separate out the baseline, in most data processing steps I think the best assumption is that this is shared among all peaks (ideally zero ofcourse).
Suggestion to make it:
```
def pdf_wrapper(time, *params):
    baseline = params[:-1]
    unpack_params = np.reshape(params[:-1], (3, -1))
    return pdf(
        time, unpack_params[0], unpack_params[1], unpack_params[2], baseline
    )
```

**Comment by Will-Robin** [comment]
Yes, I think that second snippet is the way to do it for a shared baseline. I first thought to do it this way, but then I wondered if the baseline changes over the course of a signal, you might want to capture that somehow (although a stepped change would be unusual).

We could add a caveat to the code that it is assumed the data have a constant baseline, and use a single baseline?

**Comment by thijsdejong10** [comment]
I think having a flat baseline is fine for most deconvoluted regions, since they are relatively small. If we would want to really capture a baseline that isn't flat I think y=ax+b might be a better way to go, but that is a big assumption. I think steps will give weird artifacts (as this would also try to fit the peaks).

**Comment by Will-Robin** [comment]
OK, [done](https://github.com/Will-Robin/ChromProcess/commit/487d93bbf393bc48af5fbe61b55e428b5c5dd07d).

**Comment by mgbaltussen** [comment]
Nevermind, `curve_fit` can really only handle 1 parameter array, not multiple... :(

**Comment by Will-Robin** [comment]
Thanks for the input! I've noted your contributions in the commits.
